<a href="https://colab.research.google.com/github/alexaflynn/Data/blob/main/Flynn_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loops

In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print(i)

5
6
7


In [4]:
for i in range(3):
  print("Test Number: ", i)

Test Number:  0
Test Number:  1
Test Number:  2


# Functions

In [5]:
def square(x):
    return x**2

In [6]:
square(5)

25

In [7]:
square(6)

36

In [8]:
square(square(5))

625

In [9]:
def add_two(x):
    return x+2

In [10]:
add_two(5)

7

# Logical Branching

In [11]:
choice = "apple"

In [15]:
if choice == "apple":

    print("You choose apples.")

else:
    print("You did not choose apples.")

You choose apples.


In [16]:
choice = "orange"

In [17]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:

    print("You did not choose apples or oranges.")

You choose oranges.


In [18]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:

    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


# User Input

In [20]:
choice = input("Please enter your choice (i.e. apple):")

Please enter your choice (i.e. apple):orange


In [21]:
choice

'orange'

In [22]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:

    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


In [23]:
import numpy as np

In [26]:
np.random.permutation(52)

array([39, 27, 22, 32, 13, 43, 33, 21, 47, 12,  6,  4, 37, 38, 17,  3, 19,
       36, 51, 48, 10, 16,  0, 15, 25, 50, 28,  1,  9, 49, 44, 31,  8, 30,
       26, 35, 41,  5, 20, 42, 24, 23, 11,  2, 45, 29, 46, 34, 40, 18, 14,
        7])

In [27]:
 cards = np.random.permutation(52)

In [28]:
cards

array([24, 10, 51, 15,  4, 34,  5,  8, 33, 46, 12, 45,  9, 40, 21, 50, 39,
       27, 11, 16, 47, 20, 44,  1,  7,  3, 29,  0, 48, 37, 17, 25,  6, 43,
       14, 32, 18, 36, 19, 35, 49,  2, 31, 41, 22, 26, 42, 30, 23, 38, 28,
       13])

In [29]:
cards[0]

24

In [30]:
cards[5]

34

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [32]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [33]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [34]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [35]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [36]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [37]:
suits[0]

'Clubs'

In [38]:
names[1]

'Two'

In [49]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [50]:
card_name(51)

'King of Diamonds'

In [51]:
cards = np.random.permutation(52)

In [52]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [53]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Ace of Hearts', 'Jack of Diamonds', 'Five of Spades')

In [54]:
for i in range(5):
    print(card_name(cards[i]))

Ace of Hearts
Jack of Diamonds
Three of Diamonds
Two of Diamonds
Seven of Diamonds


In [55]:
for i in range(15):
    print(card_name(cards[i]))

Ace of Hearts
Jack of Diamonds
Three of Diamonds
Two of Diamonds
Seven of Diamonds
Two of Spades
Three of Clubs
Jack of Spades
Two of Hearts
Nine of Hearts
Queen of Hearts
Three of Hearts
Seven of Hearts
Jack of Hearts
Four of Diamonds


In [56]:
card_url_head = "htpps://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [57]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [58]:
i = np.random.randint(4)
j = np.random.randint(13)

In [59]:
i,j

(3, 8)

In [60]:
suit[i]

'l'

In [61]:
card[j]

'9'

In [66]:
from IPython.core.display import display, HTML

In [62]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [63]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [70]:
show_img(img)